name: Build and Deply Snowpark Apps

on:
  push:
    branches:
      - dev
env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_DEV }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER_DEV }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE_DEV }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE_DEV }}
  SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE_DEV }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD_DEV }}
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: kilarukirankumar83/snowparkdev
          ref: dev
      - name: Setup python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install python packages
        run: pip install -r requirements.txt
      - name: Deploy snowpark apps
        working-directory: first_snowpark
        env:
            SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_DEV }}
            SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER_DEV }}
            SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE_DEV }}
            SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE_DEV }}
            SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE_DEV }}
            SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD_DEV }}
        run: python deploy_snowpark_app.py $GITHUB_WORKSPACE/first_snowpark
      - name: Deploy snowpark tasks
        working-directory: first_snowpark
        env:
            SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_DEV }}
            SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER_DEV }}
            SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE_DEV }}
            SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE_DEV }}
            SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE_DEV }}
            SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD_DEV }}
        run: python app/create_task.py



