name: Build and Deply Snowpark Apps

on:
  push:
    branches:
      - dev
env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_DEV }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER_DEV }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE_DEV }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE_DEV }}
  SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE_DEV }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD_DEV }}
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: kilarukirankumar83/snowparkdev
          ref: dev
      - name: Setup python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install python packages
        run: pip install -r requirements.txt
      - name: Copy sql files to stage
        working-directory: de_project_1/app
        run: snow stage copy load_to_emp_tgt.sql @dev_deployment/de_project_1
      - name: Deploy snowpark apps
        working-directory: de_project_1
        run: python deploy_snowpark_app.py $GITHUB_WORKSPACE/de_project_1
      - name: Deploy snowpark tasks
        working-directory: de_project_1
        run: python app/create_task.py



